---
ID: "a70e0a18-0385-40b0-a4a5-7ea6006131dd"
Parent: "2657d397-b012-4a54-9d01-6a9e5c198751"
Template: "2657d397-b012-4a54-9d01-6a9e5c198751"
Path: /sitecore/templates/Project/Collection/Headless Site/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260317T213119Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\antontishchenko@gmail.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\antontishchenko@gmail.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "629c567c-709e-4708-b7b5-91baa9f4e319"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\antontishchenko@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260317T213119Z
